// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWqD93XokK9rfQ3Rz4sWNE8W1xHsu0yVo',
    appId: '1:777272976365:web:a2f336d84dbe878e257de4',
    messagingSenderId: '777272976365',
    projectId: 'fir-auth-241ff',
    authDomain: 'fir-auth-241ff.firebaseapp.com',
    storageBucket: 'fir-auth-241ff.firebasestorage.app',
    measurementId: 'G-PYRLMXFZKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqnZv8z68aXRdJiFKcUz6kmAScyzelsGc',
    appId: '1:777272976365:android:86f21c9c00499cde257de4',
    messagingSenderId: '777272976365',
    projectId: 'fir-auth-241ff',
    storageBucket: 'fir-auth-241ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-BgGOL3cio-DvlngypTextOL_A-8eiA',
    appId: '1:777272976365:ios:629ba0a7fa0af0c5257de4',
    messagingSenderId: '777272976365',
    projectId: 'fir-auth-241ff',
    storageBucket: 'fir-auth-241ff.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-BgGOL3cio-DvlngypTextOL_A-8eiA',
    appId: '1:777272976365:ios:629ba0a7fa0af0c5257de4',
    messagingSenderId: '777272976365',
    projectId: 'fir-auth-241ff',
    storageBucket: 'fir-auth-241ff.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWqD93XokK9rfQ3Rz4sWNE8W1xHsu0yVo',
    appId: '1:777272976365:web:35921940e8c8d6e7257de4',
    messagingSenderId: '777272976365',
    projectId: 'fir-auth-241ff',
    authDomain: 'fir-auth-241ff.firebaseapp.com',
    storageBucket: 'fir-auth-241ff.firebasestorage.app',
    measurementId: 'G-0F7ZDWE15Y',
  );
}
